"""add_phase3_tables

Revision ID: 5de0768cf1f9
Revises: 67aced468c05
Create Date: 2026-06-18 12:57:03.379948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de0768cf1f9'
down_revision: Union[str, Sequence[str], None] = '67aced468c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_history() -> None:
    """Upgrade history schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_history() -> None:
    """Downgrade history schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_mind() -> None:
    """Upgrade mind schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('room', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_house_item_type', 'house', ['item_type'], unique=False)
    op.create_index('ix_house_name', 'house', ['name'], unique=True)
    op.create_index('ix_house_room', 'house', ['room'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_category', 'inventory', ['category'], unique=False)
    op.create_index('ix_inventory_name', 'inventory', ['name'], unique=True)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('breed', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('birthday', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('feeding_schedule', sa.JSON(), nullable=False),
    sa.Column('medical_conditions', sa.JSON(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('last_fed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pets_name', 'pets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade_mind() -> None:
    """Downgrade mind schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pets_name', table_name='pets')
    op.drop_table('pets')
    op.drop_index('ix_inventory_name', table_name='inventory')
    op.drop_index('ix_inventory_category', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_house_room', table_name='house')
    op.drop_index('ix_house_name', table_name='house')
    op.drop_index('ix_house_item_type', table_name='house')
    op.drop_table('house')
    # ### end Alembic commands ###


def upgrade_personality() -> None:
    """Upgrade personality schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_personality() -> None:
    """Downgrade personality schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

