"""initial_schema

Revision ID: 67aced468c05
Revises: 
Create Date: 2026-06-18 11:01:50.212329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67aced468c05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_history() -> None:
    """Upgrade history schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_turns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_history() -> None:
    """Downgrade history schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    # ### end Alembic commands ###


def upgrade_mind() -> None:
    """Upgrade mind schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mind_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mind_namespace', 'mind_records', ['namespace'], unique=False)
    op.create_index('ix_mind_namespace_key', 'mind_records', ['namespace', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade_mind() -> None:
    """Downgrade mind schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mind_namespace_key', table_name='mind_records')
    op.drop_index('ix_mind_namespace', table_name='mind_records')
    op.drop_table('mind_records')
    # ### end Alembic commands ###


def upgrade_personality() -> None:
    """Upgrade personality schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('relationship', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.String(length=16), nullable=True),
    sa.Column('food_preferences', sa.JSON(), nullable=False),
    sa.Column('hobbies', sa.JSON(), nullable=False),
    sa.Column('personality_traits', sa.JSON(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('habits', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_people_name', 'people', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade_personality() -> None:
    """Downgrade personality schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_people_name', table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###

