"""add_smart_devices_table

Revision ID: 8fbc76e8a4d2
Revises: 5de0768cf1f9
Create Date: 2026-06-26 02:22:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbc76e8a4d2'
down_revision: Union[str, Sequence[str], None] = '5de0768cf1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()


def upgrade_history() -> None:
    """Upgrade history schema."""
    pass


def downgrade_history() -> None:
    """Downgrade history schema."""
    pass


def upgrade_mind() -> None:
    """Upgrade mind schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('last_changed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_smart_devices_domain', 'smart_devices', ['domain'], unique=False)
    op.create_index('ix_smart_devices_entity_id', 'smart_devices', ['entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade_mind() -> None:
    """Downgrade mind schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_smart_devices_entity_id', table_name='smart_devices')
    op.drop_index('ix_smart_devices_domain', table_name='smart_devices')
    op.drop_table('smart_devices')
    # ### end Alembic commands ###


def upgrade_personality() -> None:
    """Upgrade personality schema."""
    pass


def downgrade_personality() -> None:
    """Downgrade personality schema."""
    pass
